---
title: "In-Class Exercise 4"
date: "30 January 2023"
date-modified: "`r Sys.Date()`"
number-sections: true
format: html
execute: 
  eval: true
  echo: true
  warning: false
editor: visual
---

Getting Started

```{r}
pacman:: p_load(maptools, sf, raster, spatstat, tmap)
```

Importing the data

```{r}
childcare_sf <- st_read("data/child-care-services-geojson.geojson") %>%
  st_transform(crs = 3414)
```
```{r}
sg_sf <- st_read(dsn = "data", layer="CostalOutline")
```

```{r}
mpsz_sf <- st_read(dsn = "data", 
                layer = "MP14_SUBZONE_WEB_PL")
```



1. Converting data from sf to spatial class
```{r}
childcare <- as_Spatial(childcare_sf)
mpsz <- as_Spatial(mpsz_sf)
sg <- as_Spatial(sg_sf)
```


2. Converting spatial class to generic sp format

Only retains the geometry, drops the data table

```{r}
childcare_sp <- as(childcare, "SpatialPoints")
sg_sp <- as(sg, "SpatialPolygons")
```

3. Converting to ppp format

List of the x and y coordinates of the points

```{r}
childcare_ppp <- as(childcare_sp, "ppp")
childcare_ppp
```


